export const reviews = [
	{
		id: 1,
		name: "Jordan D.",
		message: "Consequat cupidatat officia in pariatur nulla Lorem dolor nulla duis voluptate.",
		date: new Date("2024-12-21").getTime(),
		email: "jordan.doe@example.com",
		phone: "+123456789",
		status: "Active",
		priority: "High",
		linkedto: "HQ4540",
		rating: 5,
	},
	{
		id: 2,
		name: "Emily R.",
		message: "Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt.",
		date: new Date("2024-12-22").getTime(),
		email: "emily.rose@example.com",
		phone: "+987654321",
		status: "Pending",
		priority: "Medium",
		rating: 4,
	},
	{
		id: 3,
		name: "Michael B.",
		message: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
		date: new Date("2024-12-23").getTime(),
		email: "michael.b@example.com",
		phone: "+456789123",
		status: "Resolved",
		priority: "Low",
		rating: 3,
	},
	{
		id: 4,
		name: "Sophia L.",
		message: "Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi.",
		date: new Date("2024-12-24").getTime(),
		email: "sophia.l@example.com",
		phone: "+321654987",
		status: "Active",
		priority: "High",
		rating: 5,
	},
	{
		id: 5,
		name: "James W.",
		message: "Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore.",
		date: new Date("2025-01-06").getTime(),
		email: "james.w@example.com",
		phone: "+789123456",
		status: "Pending",
		priority: "Medium",
		rating: 4,
	},
	{
		id: 6,
		name: "Olivia P.",
		message: "Cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat.",
		date: new Date("2025-01-03").getTime(),
		email: "olivia.p@example.com",
		phone: "+654789321",
		status: "Resolved",
		priority: "Low",
		rating: 3,
	},
	{
		id: 7,
		name: "Liam T.",
		message: "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium.",
		date: new Date("2024-11-27").getTime(),
		email: "liam.t@example.com",
		phone: "+147258369",
		status: "Active",
		priority: "High",
		rating: 5,
	},
	{
		id: 8,
		name: "Emma K.",
		message: "At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis.",
		date: new Date("2024-12-30").getTime(),
		email: "emma.k@example.com",
		phone: "+369258147",
		status: "Pending",
		priority: "Medium",
		rating: 4,
	},
];
