export const data = [
	{
	  id: 1,
	  image: "img/img_trending/trending01.png",
	  title: "Adidas Ultra Boost",
	  text: "Yes",
	  price: "180",
	  stars: 4.8,
	  isTrending: true,
	  colors: ["Black", "White"],
	  description: "High-performance running shoes designed for comfort and durability.",
	  category: "Running",
	  brand: "Adidas",
	  availableSizes: [40, 41, 42, 43, 44]
	},
	{
	  id: 2,
	  image: "img/img_trending/trending02.png",
	  title: "Nike Air Max 270",
	  text: "No",
	  price: "150",
	  stars: 4.5,
	  isTrending: true,
	  colors: ["Red", "Black"],
	  description: "Stylish sneakers with excellent cushioning for everyday wear.",
	  category: "Lifestyle",
	  brand: "Nike",
	  availableSizes: [38, 39, 40, 41, 42]
	},
	{
	  id: 3,
	  image: "img/img_trending/trending03.png",
	  title: "Puma Ignite",
	  text: "Yes",
	  price: "130",
	  stars: 4.2,
	  isTrending: false,
	  colors: ["Blue", "Gray"],
	  description: "Lightweight and breathable, perfect for active lifestyles.",
	  category: "Training",
	  brand: "Puma",
	  availableSizes: [39, 40, 41, 42, 43]
	},
	{
	  id: 4,
	  image: "img/img_trending/trending04.png",
	  title: "Reebok Zig Kinetica",
	  text: "No",
	  price: "120",
	  stars: 4.0,
	  isTrending: true,
	  colors: ["White", "Orange"],
	  description: "Innovative design with energy-returning soles for optimal performance.",
	  category: "Running",
	  brand: "Reebok",
	  availableSizes: [40, 41, 42, 43, 44]
	},
	{
	  id: 5,
	  image: "img/img_trending/trending05.png",
	  title: "Converse All Star",
	  text: "Yes",
	  price: "110",
	  stars: 4.7,
	  isTrending: true,
	  colors: ["Black", "Red"],
	  description: "A timeless classic that never goes out of style.",
	  category: "Casual",
	  brand: "Converse",
	  availableSizes: [36, 37, 38, 39, 40]
	},
	{
	  id: 6,
	  image: "img/img_trending/trending06.png",
	  title: "Vans Classic",
	  text: "No",
	  price: "90",
	  stars: 4.3,
	  isTrending: false,
	  colors: ["Gray", "White"],
	  description: "Perfect for skateboarding and casual outings.",
	  category: "Skateboarding",
	  brand: "Vans",
	  availableSizes: [37, 38, 39, 40, 41]
	},
	{
	  id: 7,
	  image: "img/img_trending/trending07.png",
	  title: "New Balance 990",
	  text: "Yes",
	  price: "170",
	  stars: 4.6,
	  isTrending: true,
	  colors: ["Navy", "Gray"],
	  description: "Premium quality sneakers with exceptional arch support.",
	  category: "Walking",
	  brand: "New Balance",
	  availableSizes: [41, 42, 43, 44, 45]
	},
	{
	  id: 8,
	  image: "img/img_trending/trending08.png",
	  title: "Under Armour HOVR Phantom",
	  text: "Yes",
	  price: "160",
	  stars: 4.4,
	  isTrending: true,
	  colors: ["Black", "Blue"],
	  description: "Advanced cushioning for high-impact activities.",
	  category: "Training",
	  brand: "Under Armour",
	  availableSizes: [39, 40, 41, 42, 43]
	},
	{
	  id: 9,
	  image: "img/img_trending/trending9.png",
	  title: "Jordan Retro 4",
	  text: "No",
	  price: "200",
	  stars: 4.9,
	  isTrending: true,
	  colors: ["Red", "White"],
	  description: "Iconic basketball sneakers with a bold design.",
	  category: "Basketball",
	  brand: "Jordan",
	  availableSizes: [42, 43, 44, 45, 46]
	},
	{
	  id: 10,
	  image: "img/img_trending/trending10.png",
	  title: "Asics Gel Kayano",
	  text: "Yes",
	  price: "140",
	  stars: 4.3,
	  isTrending: false,
	  colors: ["White", "Green"],
	  description: "Designed for long-distance runners with excellent support.",
	  category: "Running",
	  brand: "Asics",
	  availableSizes: [40, 41, 42, 43, 44]
	},
	{
	  id: 11,
	  image: "img/img_trending/trending11.png",
	  title: "Saucony Endorphin",
	  text: "Yes",
	  price: "130",
	  stars: 4.1,
	  isTrending: false,
	  colors: ["Black", "Yellow"],
	  description: "Engineered for speed and responsiveness on the track.",
	  category: "Track",
	  brand: "Saucony",
	  availableSizes: [38, 39, 40, 41, 42]
	},
	{
	  id: 12,
	  image: "img/img_trending/trending12.png",
	  title: "Hoka One One Clifton",
	  text: "No",
	  price: "150",
	  stars: 4.6,
	  isTrending: true,
	  colors: ["Blue", "Orange"],
	  description: "Maximalist cushioning for unparalleled comfort during runs.",
	  category: "Running",
	  brand: "Hoka One One",
	  availableSizes: [41, 42, 43, 44, 45]
	},
	{
	  id: 13,
	  image: "img/img_trending/trending13.png",
	  title: "Adidas NMD",
	  text: "Yes",
	  price: "180",
	  stars: 4.8,
	  isTrending: true,
	  colors: ["White", "Black"],
	  description: "A sleek design blending modern aesthetics and comfort.",
	  category: "Lifestyle",
	  brand: "Adidas",
	  availableSizes: [39, 40, 41, 42, 43]
	},
	{
	  id: 14,
	  image: "img/img_trending/trending14.png",
	  title: "Nike React Infinity",
	  text: "No",
	  price: "160",
	  stars: 4.5,
	  isTrending: true,
	  colors: ["Green", "Black"],
	  description: "Built for stability and long-lasting performance.",
	  category: "Running",
	  brand: "Nike",
	  availableSizes: [40, 41, 42, 43, 44]
	},
	{
	  id: 15,
	  image: "img/img_trending/trending15.png",
	  title: "Puma Future Rider",
	  text: "Yes",
	  price: "100",
	  stars: 4.0,
	  isTrending: false,
	  colors: ["Pink", "Gray"],
	  description: "Retro-inspired sneakers with a playful touch.",
	  category: "Casual",
	  brand: "Puma",
	  availableSizes: [38, 39, 40, 41, 42]
	},
];
